# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hamza Anis
email: hamzaanis9514@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A computer scientist, not hesitated to try something new and to get better at my craft everyday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hamza9514
github_username:  HamzaAnis
facebook:
  username: hamzaanis2
  name: Qazi Hamza Anis

quora: 
  url1: https://www.quora.com/profile/Qazi-Hamza-Anis
  name: Qazi Hamza Anis  


hackerrank: 
  url: https://www.hackerrank.com/
  username: hamzaanis9514
  profile_url: https://www.hackerrank.com/hamzaanis9514
  name: Hamza Anis

stack:
  userID: 4544967
  name: Hamza Anis
  
github:
  user: hamzaanis
  repo_count: 62
  show_profile_link: true

about:
  showMe: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
